export type CategorySuggestion = { name: string; icon: string };

export const CATEGORY_SUGGESTIONS: CategorySuggestion[] = [
  { name: 'Gym', icon: 'fitness-center' },
  { name: 'Running', icon: 'directions-run' },
  { name: 'Cycling', icon: 'directions-bike' },
  { name: 'Swimming', icon: 'pool' },
  { name: 'Yoga', icon: 'self-improvement' },
  { name: 'Hair', icon: 'content-cut' },
  { name: 'Skin', icon: 'spa' },
  { name: 'Diet', icon: 'restaurant' },
  { name: 'Sleep', icon: 'bedtime' },
  { name: 'Mood', icon: 'mood' },
  { name: 'Pets', icon: 'pets' },
  { name: 'Plants', icon: 'local-florist' },
  { name: 'Weight', icon: 'bar-chart' },
  { name: 'Progress', icon: 'trending-up' },
];

export const CATEGORY_ICONS: string[] = [
  'fitness-center',
  'directions-run',
  'directions-bike',
  'pool',
  'self-improvement',
  'sports',
  'content-cut',
  'face',
  'spa',
  'restaurant',
  'local-cafe',
  'bedtime',
  'mood',
  'pets',
  'eco',
  'local-florist',
  'trending-up',
  'bar-chart',
  'accessibility-new',
  'favorite',
  'star',
  'photo-camera',
  'local-hospital',
  'music-note',
  'home',
  'work',
  'school',
  'wb-sunny',
  'directions-car',
  'flight',
];
